---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "luadns-webhook.fullname" . }}:secret-reader
  labels:
    app: {{ include "luadns-webhook.name" . }}
    chart: {{ include "luadns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [ "" ] # indicates the core API group
    resources: [ "secrets" ]
    resourceNames: [ "{{ required "tokenSecretName must be set" .Values.tokenSecretName }}" ]
    verbs: [ "get", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "luadns-webhook.fullname" . }}:secret-reader
  labels:
    app: {{ include "luadns-webhook.name" . }}
    chart: {{ include "luadns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "luadns-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "luadns-webhook.fullname" . }}:secret-reader
  apiGroup: rbac.authorization.k8s.io
